name: 'Install Octave (Linux)'
description: 'Install GNU Octave on Linux'
author: 'Ray Zimmerman'

inputs:
  ipopt-libs:  # id of input
    description: 'include installation of IPOPT libraries, if true'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Initialize Package Manager
      run: sudo apt-get update -qq
      shell: bash

    - name: Get OS version
      run: |
        OS_VER=$(grep ^VERSION_ID /etc/os-release | cut -d'=' -f2 | tr -d '"')
        echo "OS_VER=${OS_VER}" >> $GITHUB_ENV
      shell: bash

    - name: Install GNU Octave
      run: |
        if [ "$OS_VER" = "20.04" ]; then
          sudo apt-get install -y -qq liboctave-dev octave
        else
          sudo apt-get install -y -qq octave-dev octave
        fi
        ${{ inputs.ipopt-libs }} && sudo apt-get install -y -qq coinor-libipopt-dev 
        echo "ML_NAME=Octave" >> $GITHUB_ENV
        echo "ML_CMD=octave-cli --no-gui --eval" >> $GITHUB_ENV
        echo "ML_PATHVAR=OCTAVE_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Set OCTAVE_VER, ML_VER
      run: |
        export OCTAVE_VER=`$ML_CMD "fprintf('%s', ver('octave').Version)"`
        echo "OCTAVE_VER=${OCTAVE_VER}" >> $GITHUB_ENV
        echo "ML_VER=${OCTAVE_VER}" >> $GITHUB_ENV
      shell: bash

branding:
  icon: 'zap'
  color: 'yellow'
